name: digi_mess
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  localstorage: ^5.0.0
  shared_preferences: ^2.2.3
  flutter_rating_bar: ^4.0.0
  image_picker: ^0.8.4+4
  flutter_barcode_scanner: ^2.0.0
  crypto: ^3.0.3
  fl_chart: ^0.36.0
  pie_chart: ^5.0.0
  intl: ^0.19.0
  http_parser: ^4.0.2
  dio: ^5.4.3+1
  animated_splash_screen: ^1.1.0


flutter_native_splash:
  color: "#42a5f5"
  image: assets/splash.png
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/logo.jpg
    - assets/
    - assets/breakfast_veg.jpg
    - assets/breakfast_non_veg.jpg
    - assets/lunch_veg.jpg
    # - assets/lunch2.jpg
    - assets/snacks_veg.jpg
    # - assets/snacks2.jpg
    - assets/dinner_veg.jpg
    # - assets/dinner2.jpg
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg"
